# Generated by Django 4.2.7 on 2025-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_post_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
